language: java
jdk: oraclejdk8
sudo: false

script:
  - cd backend
  - mvn clean install -DskipTests=true

deploy:
  -
    on:
      branch: SNAPSHOT-0.1
    provider: script
    script: bash backend/deploy-qa.sh
