language: java
jdk: oraclejdk8
sudo: required

before_install:
  - echo "Building Backend of Inner Satisfaction"
  - cd backend
  - echo $MY_VAR

script:
  - mvn clean install -DskipTests=true

after_success:
  - echo "Build Successful for Backend of Inner Satisfaction"
  - bash deploy-qa.sh

deploy:
  - provider: script
    script: bash deploy-qa.sh
    on:
      all_branches: true
