liquibase:
  change-log: classpath:db/liquibase-changelog.xml
spring:
  datasource:
    db: inner_satisfaction
    url: jdbc:mysql://localhost:3306/${spring.datasource.db}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: none
logging:
  file: app.log
server:
  tomcat:
    accesslog:
      enabled: true
      directory: ./
    basedir: my-tomcat