spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    db: inner_satisfaction
    host: localhost
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.db}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        id.new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate.ddl-auto: none
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_DATES_AS_TIMESTAMPS: false
      write_dates_as_timestamps: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
#      READ_DATES_AS_TIMESTAMPS: false
logging:
  file: app.log
springfox.documentation.swagger.v2.path: /swagger.json
server:
  tomcat:
    accesslog:
      enabled: true
      directory: ./
    basedir: my-tomcat
person:
  images:
    path: images
# Disabled Query Logging, use commented values in order to do so
logging.level.org.hibernate:
  SQL: INFO #DEBUG
  type.descriptor.sql.BasicBinder: INFO #TRACE
management:
  endpoint:
    logfile:
      enabled: true
      cache:
        time-to-live: 100ms
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env, logfile, health, info